import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { environment } from '../../../../environment/environment';
import { GenerateReportRequest } from '../../../landing-page/models/reports-response/generate-report-request.model';
import { Observable } from 'rxjs';
import { ReportResponse } from '../../../landing-page/models/reports-response/report-response.model';

@Injectable({ providedIn: 'root' })
export class ManagerReportService {
  private http = inject(HttpClient);

  private reportsEndpoint = `${environment.BASE_URL}/api/reports`;

  /**
   * Retrieves the authenticated manager's UUID from local storage
   *
   * @description Extracts and validates the manager's unique identifier from the stored authentication token.
   * This method ensures that only authorized managers can access and generate reports for their teams,
   * maintaining proper data security and access control throughout the reporting system.
   *
   * @returns {string} The manager's UUID if authenticated, empty string if not authenticated or on error
   *
   * @throws {Alert} Shows alert dialog if manager is not logged in when parsing fails
   *
   * @example
   * ```typescript
   * const managerId = this.managerReportService.getUuid();
   * if (managerId) {
   *   // Manager is authenticated, proceed with report operations
   * }
   * ```
   */
  getUuid(): string {
    const loggedInUser = localStorage.getItem('auth');
    if (!loggedInUser) return '';
    try {
      const user = JSON.parse(loggedInUser);
      return user.uuid || null;
    } catch {
      alert('Manager not logged in!');
      return '';
    }
  }

  /**
   * Generates a custom report based on manager specifications
   *
   * @description Creates comprehensive team reports based on specified parameters including date ranges,
   * report types, employee selections, and data filters. This method supports various report formats
   * including attendance summaries, leave analytics, performance metrics, and custom team insights
   * for managerial decision-making and compliance requirements.
   *
   * @param {GenerateReportRequest} payload - Report generation parameters and specifications
   * @param {string} payload.reportType - Type of report to generate (attendance, leave, performance, etc.)
   * @param {Date} payload.startDate - Report period start date
   * @param {Date} payload.endDate - Report period end date
   * @param {string[]} [payload.employeeIds] - Optional specific employees to include
   * @param {string} [payload.format] - Report format preference (PDF, CSV, Excel)
   * @param {Object} [payload.filters] - Additional filtering criteria
   *
   * @returns {Observable<ReportResponse>} Observable containing the generated report data and metadata
   *
   * @throws {HttpError} HTTP error if report generation fails, invalid parameters, or unauthorized access
   *
   * @example
   * ```typescript
   * const reportRequest: GenerateReportRequest = {
   *   reportType: 'attendance_summary',
   *   startDate: new Date('2024-01-01'),
   *   endDate: new Date('2024-01-31'),
   *   employeeIds: ['emp-1', 'emp-2'],
   *   format: 'PDF',
   *   filters: {
   *     includeLeaveData: true,
   *     groupByDepartment: true
   *   }
   * };
   *
   * this.managerReportService.generateReportByManager(reportRequest).subscribe({
   *   next: (report) => {
   *     this.generatedReport = report;
   *     this.downloadReport(report.downloadUrl);
   *     this.showSuccess('Report generated successfully!');
   *   },
   *   error: (error) => {
   *     if (error.status === 400) {
   *       this.showError('Invalid report parameters: ' + error.error.message);
   *     } else {
   *       this.showError('Failed to generate report');
   *     }
   *   }
   * });
   * ```
   */
  generateReportByManager(
    payload: GenerateReportRequest
  ): Observable<ReportResponse> {
    const managerId = this.getUuid();

    const url = `${this.reportsEndpoint}/manager/${managerId}/generate`;

    return this.http.post<ReportResponse>(url, payload);
  }

  /**
   * Fetches recent team reports generated by the manager
   *
   * @description Retrieves a chronological list of recently generated reports for the manager's team
   * including report metadata, generation dates, parameters used, and download links. This method
   * provides report history management and enables quick access to previously generated analytics.
   *
   * @returns {Observable<ReportResponse[]>} Observable array of recent team reports with metadata
   *
   * @throws {HttpError} HTTP error if the request fails, reports are not accessible, or unauthorized access
   *
   * @example
   * ```typescript
   * this.managerReportService.fetchTeamReport().subscribe({
   *   next: (reports) => {
   *     this.recentReports = reports;
   *     this.totalReportsGenerated = reports.length;
   *     this.latestReport = reports[0]; // Most recent report
   *
   *     // Categorize reports by type
   *     this.attendanceReports = reports.filter(r => r.reportType === 'attendance');
   *     this.leaveReports = reports.filter(r => r.reportType === 'leave');
   *     this.performanceReports = reports.filter(r => r.reportType === 'performance');
   *   },
   *   error: (error) => console.error('Failed to load team reports:', error)
   * });
   *
   * // Usage in template for report history table
   * // <tr *ngFor="let report of recentReports">
   * //   <td>{{ report.reportName }}</td>
   * //   <td>{{ report.generatedDate | date }}</td>
   * //   <td><a [href]="report.downloadUrl">Download</a></td>
   * // </tr>
   * ```
   */
  fetchTeamReport(): Observable<ReportResponse[]> {
    const managerId = this.getUuid();

    const url = `${this.reportsEndpoint}/manager/${managerId}/recent`;

    return this.http.get<ReportResponse[]>(url);
  }
}
